line-length = 100

[lint]
select = ["E", "F", "W", "I", "UP", "B", "PL"]
ignore = [
  # Let Black handle formatting-related concerns
  "E501",
]

[lint.isort]
known-first-party = []

[format]
quote-style = "preserve"
indent-style = "space"
line-ending = "lf"
