name: Test Download Logic

on:
  push:
  workflow_dispatch:  # Allow manual triggering
  pull_request:
    branches: [ main ]
    paths:
      - 'tools/utils.py'  # Run when utils.py is modified

jobs:
  test-download:
    runs-on: tt-beta-ubuntu-2204-n150-large-stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests torch tabulate

      - name: Test get_file function directly
        run: |
          # Test if we can get the cached file in Civ2 environment
          # Set environment variable
          export DOCKER_CACHE_ROOT="/tmp/docker_cache_test"

          # Run simple test
          cd $GITHUB_WORKSPACE
          python -c "
          from tools.utils import get_file
          import os

          # Call get_file function
          test_file_path = 'test_files/pytorch/yolov10/yolov_10n.pt'
          print(f'Testing get_file with path: {test_file_path}')
          result_path = get_file(test_file_path)
          print(f'File returned by get_file: {result_path}')
          "
          ls $DOCKER_CACHE_ROOT/models/tt-ci-models-private/test_files/pytorch/yolov10
